### ISSUE TITLE
Hosting on RubyGems?

### ISSUE THREAD

**Issue by JSFernandes** [getonbrd/pipedrive-connect#14]
Hello,

I am starting to use this gem in a project, and am wondering why my only option to use it is by adding a direct GitHub link on the Gemfile. Even with Gemfile.lock enforcing the revision, I would feel more comfortable with managed versions on something like RubyGems. Is there a particular reason why this gem isn't available there?

**Comment by j4rs** [comment]
Hey @JSFernandes,

I really have no excuse, it was laziness or carelessness from my part, here it is remedied https://rubygems.org/gems/pipedrive-connect

Let me know whether it works or I can do anything else and thanks for using the gem.

**Comment by JSFernandes** [comment]
@j4rs Thank you for the quick response and action. The version on rubygems is working fine for us.
