### ISSUE TITLE
WARNING: No adapter was configured for this request

### ISSUE THREAD

**Issue by krivitsky** [getonbrd/pipedrive-connect#22]
I'm testing the API and getting an error

```
require 'pipedrive'
Pipedrive.api_key = "abc123"

Pipedrive::Organization.retrieve(1)
WARNING: No adapter was configured for this request

Traceback (most recent call last):
        1: from (irb):5
TypeError (no implicit conversion of nil into String)
```

The same goes for other objects and methods. What am I doing wrong?
Ruby: 2.6.5

Thanks

**Comment by j4rs** [comment]
Hello, which version are you using? you can get it by calling `Pipedrive::VERSION` - It is all working fine here with the last version **1.2.9**

**Comment by j4rs** [comment]
Maybe check what version of the **faraday** gem you are using (_it is the only dependency of this gem_) and try updating it to a more recent one.

**Comment by j4rs** [comment]
Closing this as there is no new update and the problem doesn't seem to be related with the gem.
