### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by f-g-p** [getonbrd/pipedrive-connect#27]
Hello,
it seems that you have a typo in the readme doc (extact_match instead of exact_match).
I suppose it should be corrected because it bit us hard (our fault, we shouldn't have copy pasted, and tested better).
I would have opened a PR directly but I am not authorized to do so.

Thanks for the gem!

ps: side question: We noticed the issue because using extact_match resulted in having `exact_match` set to false, and thus an unexpected organization was returned in our search. But our search was specifying one field (our system id), and the returned item did not match the id at all, but had the searched id as part of its phone number.
I'm puzzled that it was returned since I am searching only on my custom id field, and not on phone number. 
Any idea of what could have happened ?

**Comment by j4rs** [comment]
Good catch 🦅  - Typo fixed. Thank you for this.
